version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./backup:/backup
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: narg
      MYSQL_DATABASE: test_db
      MYSQL_USER: narg
      MYSQL_PASSWORD: narg
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    networks:
      - mysql_net

networks:
  mysql_net:
    driver: bridge