version: "3.9"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "nargdb"
      POSTGRES_USER: "narg"
      POSTGRES_PASSWORD: "narg"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./backup:/backup
      - .:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "narg@narg.com"
      PGADMIN_DEFAULT_PASSWORD: "narg"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge