version: "3.9"
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: "nargdb"
      POSTGRES_USER: "narg"
      POSTGRES_PASSWORD: "narg"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./backup:/backup
      - .:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge